"""
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 
10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

if __name__ == "__main__":
	prim = 1
	seg = 2
	terc = prim+seg
	sumaPares = 2
	while terc < 4*(10**6):
		if terc%2 == 0:
			sumaPares += terc
		prim = seg
		seg = terc
		terc = prim+seg

	print sumaPares
